apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend
  namespace: ns_name
spec:
  parentRefs:
    - name: gateway
      sectionName: http
      namespace: gateway
  hostnames:
    - "phrases.local"
  rules:
    - matches:
        - path:
            type: PathPrefix # Matches any path starting with /coffee
            value: "/"
      backendRefs:
        - name: frontend
          port: 8080
    - matches:
        - path:
            type: PathPrefix # Matches any path starting with /coffee
            value: "/metrics"
      backendRefs:
        - name: frontend
          port: 8080